# Generated by Django 5.2.4 on 2025-07-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacherprofile_bio_teacherprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
