# Generated by Django 5.2.4 on 2025-07-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
